### ISSUE TITLE
[SET] - Invalid set is returning success

### ISSUE THREAD

**Issue by andrewfreitas** [yeahoffline/redis-mock#129] opened 2020-02-18 15:37 UTC
Sendind a set command with invalid keys or invalid values are returning success. It need to return an error.

For example, a set command passing a null key is returning success.

**Comment by kamiljano** [comment] 2020-11-23 07:07
looks like there even was a test to make sure that we do just that... validated with the `redis` module and confirmed that this is not the wanted behaviour. This should be fixed, along with a bunch of other closely related things over here: https://github.com/yeahoffline/redis-mock/pull/149

**Closed** 2020-11-27 10:54 UTC
